# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 26763412448a86c810b089b5fccaf3bcd17b17439929c908abf568504872f8024c652532f0891c1f4331e136b6e30881513f4f9c389c2ba9b2c319d2989f9c83

test:
  secret_key_base: 7baa9e53ecff075445f8ae9e509871ad80481c0bb35865c30bc00404a64cb742e70dcc5f94e4bc98fa4d109e639badfbbae6f0128423ad942f8d6d5aec9eaeeb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
